### ISSUE TITLE
Not compiling erlexec dependency in mac os 10.13.3

### ISSUE THREAD

**Issue by batok** [rkallos/wrek_examples#1]
Hi,

I tried this but erlexec fails to compile in mac os 10.13.3 ( High Sierra ).  I wonder if erlexec just works in linux or other nix, but mac os x?  
![screen shot 2018-03-20 at 6 09 08 pm](https://user-images.githubusercontent.com/29124/37689305-e0bed038-2c69-11e8-859e-daf0db692bb9.png)

**Comment by rkallos** [comment]
Hi Domingo. Sorry for not getting back sooner. This slipped through the radar.

Erlexec reportedly works on macos, but I have never tried getting it to work on that platform. If you look [here](https://github.com/saleyn/erlexec/blob/7a00673044a3037310cb3a15ff829a879f41d6a8/rebar.config.script#L51), you can see that `HAS_SETREUID` is supposed to be set when rebar3 builds exec.cpp. However, I cannot tell from your screenshot whether rebar3 sets it properly. Would you be willing to retry using `DEBUG=1 rebar3 compile`, and posting the output somewhere? That might give us some more information.

For now, I'm going to try and do 2 things:

1. I will upgrade the erlexec dependency in wrek to use the latest version (1.7.4 at the time of this writing). Who knows, perhaps this issue has already been fixed.
2. I will try and see if erlexec successfully compiles on a coworker's Macbook.

Thank you very much for bringing this to my attention. I apologize once again for the late reply.

**Comment by batok** [comment]
It worked with change to 1.7.4 .  I tried changing rebar.config and worked.

`diff --git a/rebar.config b/rebar.config
index e7df1ac..ebc7a01 100644
--- a/rebar.config
+++ b/rebar.config
@@ -1,5 +1,5 @@
 {erl_opts, [debug_info]}.
 {deps, [
   {wrek, "0.0.1",
-    {git, "https://github.com/rkallos/wrek.git", {tag, "0.0.1"}}}
-]}.
\ No newline at end of file
+    {git, "https://github.com/rkallos/wrek.git", {branch, "master"}}}
+]}.`

**Comment by rkallos** [comment]
I've since released wrek 2.0.0 which uses erlexec 1.7.4, so I'll be marking this issue as closed. Thank you very much for bringing this to my attention!
